# Copyright 2014 Ronoaldo JLP <ronoaldo@gmail.com>
# Licensed under the Apache License, Version 2.0

runtime: go
api_version: go1

handlers:
- url: /assets
  static_dir: assets

- url: /.*
  script: _go_app
  login: admin
